[project]
name = "mark-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax>=0.6.0",
    "polars>=1.27.1",
    "yfinance>=0.2.55",
]
